### ISSUE TITLE
Error on upgrade to Spring Boot 1.5.x & 2.x.x

### ISSUE THREAD

**Issue by hendisantika** [ekomanurung/spring-boot-web-kafka-producer-mongoDB#1]
Nice repo.

But I have error when upgrade to Spring Boot 1.5.x & 2.x.x.

Could You please upgraded into latest version?

Thanks

**Comment by ekomanurung** [comment]
thank you for visiting my repositories. sorry for late update, i just updated it into new version of springboot 1.15.4, and it works well. thank you very much
