### ISSUE TITLE
Upgrade ke latest version

### ISSUE THREAD

**Issue by hendisantika** [ekomanurung/spring-boot-web-kafka-producer-mongoDB#2]
Bisa Upgrade ke latest version?

Thanks

**Comment by ekomanurung** [comment]
Done

**Comment by hendisantika** [comment]
Nuhun pisan...

Coba icip2 lagi ah.... 🫸🌀✏️📗🐧🐳⬆

**Comment by hendisantika** [comment]
Gak langsung ke JDK21 aja bang @ekomanurung ?

**Comment by ekomanurung** [comment]
boleh om. updated dsni: [MR](https://github.com/ekomanurung/spring-boot-web-kafka-producer-mongoDB/pull/7)
